#!/bin/bash
gh issue create --title "Feature: Response Models & Return Type Extraction" --body "Implement automatic JSON schema generation for response bodies by inspecting return type annotations or a dedicated response_model parameter."
gh issue create --title "Feature: Reusable Component Schemas (\$ref)" --body "Register complex structures in components/schemas and reference them using \$ref to clean up openapi.json."
gh issue create --title "Feature: Grouping and Tags for OpenAPI" --body "Support tags on route decorators (e.g., @app.get('/users', tags=['Users'])) to group endpoints in Swagger UI."
gh issue create --title "Feature: Header and Cookie Parameters" --body "Extract HTTP Headers and Cookies as parameters in the OpenAPI schema."
gh issue create --title "Feature: Security Schemes & Authentication" --body "Support OpenAPI securitySchemes (e.g., OAuth2, Bearer tokens, API Keys) and applying them to endpoints."
gh issue create --title "Feature: Multipart Form Data and File Uploads" --body "Support multipart/form-data and application/x-www-form-urlencoded payloads for documentation."
gh issue create --title "Feature: Custom Response Codes and Examples" --body "Provide a mechanism to document custom error codes and example payloads via route decorators."
gh issue create --title "Feature: Deprecation Flags" --body "Support a deprecated=True flag in route decorators."
gh issue create --title "Feature: Advanced Validation Constraints" --body "Integrate BustAPI's custom validators (like String, Integer subclasses) constraints into the OpenAPI schema."
